AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Nested stacks - Root template (uksb-1q9p31idr) (tag:nested-stacks).

Parameters:
  AvailabilityZones:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The list of Availability Zones to use for the subnets in the VPC. Select 2 AZs.

  VPCName:
    Type: String
    Description: The name of the VPC.
    Default: Lab6.2

  VPCCidr:
    Type: String
    Description: The CIDR block for the VPC.
    Default: 10.72.0.0/16

  PublicSubnet1Cidr:
    Type: String
    Description: The CIDR block for the public subnet located in Availability Zone 1.
    Default: 10.72.32.0/24

  PrivateSubnet1Cidr:
    Type: String
    Description: The CIDR block for the public subnet located in Availability Zone 2.
    Default: 10.72.0.0/24

  PrivateSubnet2Cidr:
    Type: String
    Description: The CIDR block for the public subnet located in Availability Zone 2.
    Default: 10.72.1.0/24

  DBInstanceIdentifier:
    Type: String
    Description: tên duy nhất cho DB instance.
    Default: lab62rdssss

  DBName:
    Type: String
    Description: Tên của cơ sở dữ liệu ban đầu mà bạn muốn tạo trong phiên bản RDS này
    Default: OODWHOR

  MasterUsername:
    Type: String
    Description: Tên người dùng chính cho phiên bản RDS.
    Default: Lab62Abcd12346L

  MasterUserPassword:
    Type: String
    Description: Mật khẩu cho tài khoản người dùng chính (master user).
    Default: Lab62Abcd1234!

  DBInstanceClass:
    Type: String
    Default: db.m5.large

  AllocatedStorage:
    Type: Number
    Default: "20"

  StorageType:
    Type: String
    Default: gp3

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://lab62s3bucket-s3bucket-zfula7svttvc.s3.amazonaws.com/vpc.yaml
      TimeoutInMinutes: 20
      Parameters:
        AvailabilityZones:
          Fn::Join:
            - ","
            - !Ref AvailabilityZones
        VPCCidr: !Ref VPCCidr
        VPCName: !Ref VPCName
        PublicSubnetCidr: !Ref PublicSubnet1Cidr
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr: !Ref PrivateSubnet2Cidr

  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VpcStack
    Properties:
      TemplateURL: !Sub https://lab62s3bucket-s3bucket-zfula7svttvc.s3.amazonaws.com/rds.yaml
      TimeoutInMinutes: 20
      Parameters:
        RDSAZ: !Select [0, !Ref AvailabilityZones]
        DBInstanceIdentifier: !Ref DBInstanceIdentifier
        DBName: !Ref DBName
        MasterUsername: !Ref MasterUsername
        MasterUserPassword: !Ref MasterUserPassword
        DBInstanceClass: !Ref DBInstanceClass
        AllocatedStorage: !Ref AllocatedStorage
        StorageType: !Ref StorageType
